# Generated by Django 5.2.5 on 2025-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('FUNDAMENTAL', 'Ensino Fundamental'), ('MEDIO', 'Ensino Médio'), ('SUPERIOR', 'Ensino Superior'), ('POS_GRADUACAO', 'Pós-Graduação'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('LICENSEE', 'Permissionário'), ('BUSINESS', 'Perfil Empresarial'), ('EDUCATIONAL', 'Perfil Educacional')], max_length=11, verbose_name='Tipo de Usuário'),
        ),
    ]
