# Generated by Django 5.2.5 on 2025-08-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_customuser_date_of_birth_customuser_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-mail Verificado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de Verificação'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Código'),
        ),
    ]
