# Generated by Django 5.2.5 on 2025-08-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_management', '0003_alter_company_owner_changerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCMChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Capítulo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='NCMPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Posição')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='showcase_management.ncmchapter', verbose_name='Capítulo')),
            ],
        ),
        migrations.CreateModel(
            name='NCMSubitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Subitem')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='showcase_management.ncmposition', verbose_name='Posição')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company_management.company', verbose_name='Empresa')),
                ('ncm_subitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='showcase_management.ncmsubitem', verbose_name='NCM (Subitem)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Imagem')),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True, verbose_name='Aprovada')),
                ('moderator_notes', models.TextField(blank=True, null=True, verbose_name='Notas do Moderador')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='showcase_management.product', verbose_name='Produto')),
            ],
        ),
    ]
