# Generated by Django 5.2.5 on 2025-08-25 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código CNAE')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'Gerenciamento de CNAEs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('institutional_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato Institucional')),
                ('institutional_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Institucional')),
                ('address', models.TextField(verbose_name='Endereço Principal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logotipo')),
                ('legal_rep_name', models.CharField(max_length=255, verbose_name='Nome Completo do Responsável')),
                ('legal_rep_role', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('legal_rep_contact', models.CharField(max_length=20, verbose_name='Contato Direto/WhatsApp')),
                ('legal_rep_email', models.EmailField(max_length=254, verbose_name='Email do Responsável')),
                ('status', models.CharField(choices=[('REVIEW', 'Em Análise'), ('ACTIVE', 'Ativa'), ('REJECTED', 'Recusada')], default='REVIEW', max_length=10, verbose_name='Status')),
                ('moderation_notes', models.TextField(blank=True, null=True, verbose_name='Justificativa/Notas de Moderação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_activity_companies', to='company_management.cnae', verbose_name='Atividade Principal (CNAE)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Gerenciamento de Empresas',
            },
        ),
    ]
