# Generated by Django 5.2.5 on 2025-08-25 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'BUSINESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário (Perfil Empresarial)'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_activities',
            field=models.ManyToManyField(blank=True, related_name='secondary_activity_companies', to='company_management.cnae', verbose_name='Atividades Secundárias (CNAE)'),
        ),
    ]
