# Generated by Django 5.2.5 on 2025-08-25 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário (Perfil Empresarial)'),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_changes', models.JSONField(verbose_name='Dados Solicitados')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=10, verbose_name='Status da Solicitação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Moderação')),
                ('moderator_notes', models.TextField(blank=True, null=True, verbose_name='Notas do Moderador')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='company_management.company', verbose_name='Empresa')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração',
                'verbose_name_plural': 'Solicitações de Alteração',
            },
        ),
    ]
