# Generated by Django 5.2.5 on 2025-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100, verbose_name='Título do Card')),
                ('card_image', models.ImageField(upload_to='intelligence_cards/', verbose_name='Imagem do Card')),
                ('title', models.CharField(max_length=200, verbose_name='Título Principal da Página')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('content', models.TextField(verbose_name='Conteúdo da Análise')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Análise',
                'verbose_name_plural': 'Páginas de Análise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Interno do Gráfico')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para o shortcode, gerado automaticamente.', unique=True)),
                ('options_json', models.JSONField(verbose_name='Opções de Configuração (JSON do ECharts)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gráfico',
                'verbose_name_plural': 'Gráficos',
            },
        ),
    ]
