# Generated by Django 5.2.5 on 2025-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='options_json',
            field=models.JSONField(help_text='Cole aqui o JSON VÁLIDO. Dica: cole o código do exemplo do ECharts em uma IA (ChatGPT, Gemini, etc.) ou em um conversor online e peça para converter para JSON válido.', verbose_name='Opções de Configuração (JSON do ECharts)'),
        ),
    ]
