# Generated by Django 5.2.5 on 2025-08-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_market', '0002_alter_chart_options_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='options_json',
        ),
        migrations.AddField(
            model_name='chart',
            name='options_js',
            field=models.TextField(default={}, help_text="Cole aqui o objeto 'option' diretamente do exemplo do ECharts. Ex: { title: { text: 'Meu Gráfico' }, ... }", verbose_name='Opções de Configuração (Código JavaScript do ECharts)'),
            preserve_default=False,
        ),
    ]
