# Generated by Django 5.2.5 on 2025-08-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('order', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição das categorias.')),
            ],
            options={
                'verbose_name': 'Categoria de FAQ',
                'verbose_name_plural': 'Categorias de FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição das perguntas dentro de uma categoria.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='support_management.faqcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['order'],
            },
        ),
    ]
