# Generated by Django 5.2.5 on 2025-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome/Descrição do Recurso')),
                ('asset_type', models.CharField(choices=[('LOGO_PLATAFORMA', 'Logo da Plataforma (Header)'), ('LOGO_GOVERNO', 'Logo do Governo/Secretaria (Header)'), ('LOGO_PARCEIRO', 'Logo de Parceiro (Rodapé)')], max_length=20, verbose_name='Tipo do Recurso')),
                ('image', models.ImageField(upload_to='site_assets/', verbose_name='Arquivo de Imagem')),
                ('url_link', models.URLField(blank=True, null=True, verbose_name='Link (Opcional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição para parceiros.')),
            ],
            options={
                'verbose_name': 'Recurso do Site',
                'verbose_name_plural': 'Recursos do Site',
                'ordering': ['order'],
            },
        ),
    ]
